"""Export a converged canceller as a C header for a bare-metal DSP.

    python demos/03_vibration_cancellation/emit_c_header.py
    python demos/03_vibration_cancellation/emit_c_header.py --algorithm NLMS

Trains the chosen algorithm at the chosen precision, then writes the
converged tap vector plus the adaptation parameters as C89-compatible
constants with no includes.

Why the taps and the step size ship together
--------------------------------------------
The tap vector alone is a *fixed* filter — it cancels the disturbance the
demo trained on and nothing else. A real installation keeps adapting, so the
header carries the step size (or forgetting factor) as well: the taps are the
warm start, and the parameters are how the target continues from there.
Shipping only the taps would silently turn an adaptive canceller into a
fixed one, which works until the machine changes speed.

A diverged run has no taps worth exporting, so the exporter refuses rather
than writing NaNs into a header destined for an actuator loop.
"""

from __future__ import annotations

import argparse
from pathlib import Path

import numpy as np

import mpdsp

from design import ALGORITHMS, NUM_TAPS, train
from simulate import synthesize

_BANNER = """\
/*
 * {name} — active vibration canceller
 *
 * Generated by demos/03_vibration_cancellation/emit_c_header.py
 * — do not edit.
 *
 * Algorithm : {algorithm}
 * Precision : trained in '{dtype}'
 * Taps      : {num_taps}
 * Rate      : {sample_rate:.1f} Hz
 * Converged : {reduction:.1f} dB residual reduction
 *             (sensor floor caps this at ~{achievable:.0f} dB)
 * Design    : mpdsp {version} (upstream sw::dsp {dsp_version})
 *
 * The filter output is the ANTI-signal: drive the actuator with -y[n].
 *
 *     y[n] = sum_{{k=0}}^{{N-1}} w[k] * x[n-k]
 *     e[n] = d[n] - y[n]                (residual at the error sensor)
 *
 * These weights are a warm start, not a final answer. Keep adapting on the
 * target with the parameters below, or the canceller stops working the
 * first time the machine changes speed.
 */
"""


def _guard(name: str) -> str:
    return "".join(c.upper() if c.isalnum() else "_" for c in name)


def render_header(algorithm: str = "NLMS", dtype: str = "reference",
                  num_samples: int = 24000, name: str = "canceller.h") -> str:
    """Train and render. Raises if the run did not converge."""
    if algorithm not in ALGORITHMS:
        raise ValueError(f"unknown algorithm {algorithm!r}; "
                         f"expected one of {sorted(ALGORITHMS)}")

    reference, primary, meta = synthesize(num_samples=num_samples)
    result = train(algorithm, dtype, reference, primary, meta)

    if result.diverged:
        raise ValueError(
            f"{algorithm} at '{dtype}' diverged ({result.notes}) — refusing "
            f"to export. Weights from a diverged run are NaN or unbounded, "
            f"and a header destined for an actuator loop is the last place "
            f"to discover that.")
    if result.amplified:
        raise ValueError(
            f"{algorithm} at '{dtype}' amplified the disturbance by "
            f"{-result.reduction_db:.1f} dB — refusing to export. These "
            f"weights would drive the structure, not cancel it.")

    guard = _guard(name)
    weights = np.asarray(result.weights)

    lines = [_BANNER.format(
        name=name, algorithm=algorithm, dtype=dtype, num_taps=len(weights),
        sample_rate=meta["sample_rate"], reduction=result.reduction_db,
        achievable=meta["achievable_reduction_db"],
        version=mpdsp.__version__, dsp_version=mpdsp.__dsp_version__)]

    lines.append(f"#ifndef {guard}")
    lines.append(f"#define {guard}")
    lines.append("")
    lines.append(f"#define CANCELLER_NUM_TAPS   {len(weights)}")
    lines.append(f"#define CANCELLER_RATE_HZ    {meta['sample_rate']:.1f}")
    lines.append("")

    lines.append("/* Converged tap weights, oldest sample last. */")
    lines.append("static const double canceller_taps[CANCELLER_NUM_TAPS] = {")
    for start in range(0, len(weights), 4):
        row = ", ".join(f"{w:.17g}" for w in weights[start:start + 4])
        lines.append(f"    {row},")
    lines.append("};")
    lines.append("")

    lines.append("/* Adaptation parameters — keep adapting on the target. */")
    if algorithm == "LMS":
        lines.append("#define CANCELLER_ALGORITHM  \"LMS\"")
        lines.append("#define CANCELLER_STEP_SIZE  0.01")
    elif algorithm == "NLMS":
        lines.append("#define CANCELLER_ALGORITHM  \"NLMS\"")
        lines.append("#define CANCELLER_STEP_SIZE  0.3")
        lines.append("#define CANCELLER_EPSILON    1e-06")
    else:
        lines.append("#define CANCELLER_ALGORITHM  \"RLS\"")
        lines.append("#define CANCELLER_FORGETTING 0.999")
        lines.append("#define CANCELLER_DELTA      1000.0")
        lines.append("/* RLS is precision-fragile: see the README before")
        lines.append(" * porting this one to anything narrower than double. */")
    lines.append("")

    lines.append(f"#endif /* {guard} */")
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--algorithm", default="NLMS", choices=list(ALGORITHMS),
                        help="default NLMS: converges as well as LMS here and "
                             "is far less sensitive to input level")
    parser.add_argument("--dtype", default="reference")
    parser.add_argument("--num-samples", type=int, default=24000)
    parser.add_argument("--out", default=None)
    args = parser.parse_args()

    out = (Path(args.out) if args.out
           else Path(__file__).parent / "artifacts" / "canceller.h")
    out.parent.mkdir(parents=True, exist_ok=True)

    try:
        text = render_header(args.algorithm, args.dtype, args.num_samples,
                             name=out.name)
    except ValueError as exc:
        print(f"error: {exc}")
        return 1

    out.write_text(text)
    print(f"wrote {out} ({out.stat().st_size} bytes, "
          f"{args.algorithm} trained in '{args.dtype}', "
          f"{NUM_TAPS} taps)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
