"""Export the designed chain as a C header for a bare-metal target.

The design work happens in Python; the deployed filter is a handful of
constants. This writes those constants — three biquads plus the compressor
and limiter parameters — as a self-contained header that a DSP toolchain can
include without pulling in any of this repository.

    python demos/01_audio_dynamics/emit_c_header.py --out artifacts/chain.h

The header is C89-compatible and has no includes, so it drops into a
bare-metal project unchanged. Coefficients are emitted with 17 significant
digits, which round-trips IEEE double exactly.

Passing `--coeff-dtype` designs the coefficients at a narrower precision
before export, which is how you check what a target's design-time arithmetic
would have produced. The emitted values are always `double` literals; narrow
them at the point of use with the target's own type.
"""

from __future__ import annotations

import argparse
from pathlib import Path

import mpdsp

from design import ChainConfig, design_eq

_BANNER = """\
/*
 * {name} — audio dynamics chain coefficients
 *
 * Generated by demos/01_audio_dynamics/emit_c_header.py — do not edit.
 *
 * Chain:  lowshelf -> peaking -> highshelf -> compressor -> peak limiter
 * Rate:   {sample_rate:.1f} Hz
 * Design: mpdsp {version} (upstream sw::dsp {dsp_version}),
 *         coefficients computed in '{coeff_dtype}'
 *
 * Biquads are transposed-direct-form-II ready: for each stage,
 *
 *     y[n] = b0*x[n] + b1*x[n-1] + b2*x[n-2] - a1*y[n-1] - a2*y[n-2]
 *
 * with a0 already normalized to 1. Stage order is the array order.
 *
 * The mid band is a PARALLEL path, not a series stage:
 *
 *     y = x + (MID_GAIN - 1) * biquad(mid, x)
 *
 * Applying it in series would strip everything outside the mid band.
 */
"""


def _guard(name: str) -> str:
    return "".join(c.upper() if c.isalnum() else "_" for c in name)


def render_header(config: ChainConfig, name: str = "chain.h") -> str:
    """Return the full text of the generated header."""
    eq = design_eq(config)
    guard = _guard(name)

    lines = [_BANNER.format(
        name=name,
        sample_rate=config.sample_rate,
        version=mpdsp.__version__,
        dsp_version=mpdsp.__dsp_version__,
        coeff_dtype=config.coeff_dtype,
    )]
    lines.append(f"#ifndef {guard}")
    lines.append(f"#define {guard}")
    lines.append("")
    lines.append(f"#define CHAIN_SAMPLE_RATE_HZ  {config.sample_rate:.1f}")
    lines.append("#define CHAIN_NUM_BIQUADS     3")
    lines.append("")

    lines.append("/* Biquad sections, in signal order: low, mid, high. */")
    lines.append("typedef struct {")
    lines.append("    double b0, b1, b2, a1, a2;")
    lines.append("} chain_biquad_t;")
    lines.append("")
    lines.append("static const chain_biquad_t "
                 "chain_biquads[CHAIN_NUM_BIQUADS] = {")
    for band, filt in (("low  (lowshelf)", eq["low"]),
                       ("mid  (bandpass, parallel)", eq["mid"]),
                       ("high (highshelf)", eq["high"])):
        b0, b1, b2, a1, a2 = filt.coefficients()[0]
        lines.append(f"    /* {band} */")
        lines.append(f"    {{ {b0:.17g}, {b1:.17g}, {b2:.17g}, "
                     f"{a1:.17g}, {a2:.17g} }},")
    lines.append("};")
    lines.append("")

    lines.append("/* Parallel mix weight for the mid band: y = x + "
                 "(CHAIN_MID_GAIN - 1) * mid(x). */")
    lines.append(f"#define CHAIN_MID_GAIN_DB     {config.mid_gain_db:.17g}")
    lines.append(f"#define CHAIN_MID_GAIN        "
                 f"{10.0 ** (config.mid_gain_db / 20.0):.17g}")
    lines.append("")

    lines.append("/* Compressor. */")
    for macro, value in (
            ("CHAIN_COMP_THRESHOLD_DB", config.threshold_db),
            ("CHAIN_COMP_RATIO", config.ratio),
            ("CHAIN_COMP_ATTACK_MS", config.attack_ms),
            ("CHAIN_COMP_RELEASE_MS", config.release_ms),
            ("CHAIN_COMP_MAKEUP_DB", config.makeup_db),
            ("CHAIN_COMP_KNEE_DB", config.knee_db)):
        lines.append(f"#define {macro:<26}{value:.17g}")
    lines.append("")

    lines.append("/* Peak limiter. Lookahead is in samples at the rate above; "
                 "the")
    lines.append(" * gain path needs the audio delayed by that much. */")
    lookahead = max(1, int(round(config.limiter_lookahead_ms
                                 * config.sample_rate / 1000.0)))
    for macro, value in (
            ("CHAIN_LIMIT_CEILING", f"{config.ceiling:.17g}"),
            ("CHAIN_LIMIT_ATTACK_MS", f"{config.limiter_attack_ms:.17g}"),
            ("CHAIN_LIMIT_RELEASE_MS", f"{config.limiter_release_ms:.17g}"),
            ("CHAIN_LIMIT_LOOKAHEAD_MS",
             f"{config.limiter_lookahead_ms:.17g}"),
            ("CHAIN_LIMIT_LOOKAHEAD_SAMPLES", str(lookahead))):
        lines.append(f"#define {macro:<32}{value}")
    lines.append("")

    lines.append(f"#endif /* {guard} */")
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--out", default=None,
                        help="Output path (default: ./artifacts/chain.h "
                             "next to this script)")
    parser.add_argument("--sample-rate", type=float, default=None)
    parser.add_argument("--coeff-dtype", default="reference",
                        help="Design the coefficients at this precision "
                             "before exporting")
    args = parser.parse_args()

    out = (Path(args.out) if args.out
           else Path(__file__).parent / "artifacts" / "chain.h")

    config = ChainConfig(coeff_dtype=args.coeff_dtype)
    if args.sample_rate:
        config.sample_rate = args.sample_rate

    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(render_header(config, name=out.name))
    print(f"wrote {out} ({out.stat().st_size} bytes, "
          f"coefficients designed in '{config.coeff_dtype}')")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
