"""Export the current-loop controller and notch as a C header.

    python demos/02_motor_servo/emit_c_header.py
    python demos/02_motor_servo/emit_c_header.py --design-point aggressive \
        --dtype fpga_fixed

Writes the PI difference equation and the notch biquad as C89-compatible
constants with no includes, so it drops into a C2000 Code Composer Studio
project or an STM32Cube one unchanged.

The exporter refuses to emit a configuration whose closed loop is unstable
at the requested precision. A motor controller header is a bad place to
find out that the coefficients you shipped put a pole on the unit circle.
"""

from __future__ import annotations

import argparse
from pathlib import Path

import numpy as np

import mpdsp

from design import (DEFAULT_DTYPES, DESIGN_POINTS, _quantize, design_notch,
                    design_pi, sweep)
from simulate import SAMPLE_RATE_HZ, Motor

_BANNER = """\
/*
 * {name} — BLDC current-loop controller
 *
 * Generated by demos/02_motor_servo/emit_c_header.py — do not edit.
 *
 * Design point : {point} ({rationale})
 * Precision    : coefficients quantized to '{dtype}'
 * Loop rate    : {rate:.1f} Hz
 * Crossover    : {crossover:.0f} Hz
 * Notch        : {notch:.0f} Hz, {notch_bw:.1f} octave, {depth:.0f} dB deep
 * Closed loop  : max|pole| = {max_pole:.5f}, overshoot {overshoot:.1f}%
 * Plant        : R = {resistance:.4f} Ohm, L = {inductance:.3g} H,
 *                tau = {tau:.1f} us
 * Design       : mpdsp {version} (upstream sw::dsp {dsp_version})
 *
 * Loop order, once per current sample:
 *
 *     err  = i_ref - i_meas;
 *     u    = pi_step(err);        // PI, integrator state
 *     u    = notch_step(u);       // biquad, direct form I
 *     apply u as the voltage command
 *
 * The PI zero sits on the plant pole, so PI_B1 is -exp(-T/tau) and depends
 * on the motor. Re-run this exporter if R or L change; a controller tuned
 * for a different winding is not merely suboptimal, it moves the
 * cancellation and leaves a slow doublet in the response.
 */
"""


def _guard(name: str) -> str:
    return "".join(c.upper() if c.isalnum() else "_" for c in name)


def render_header(design_point: str = "conservative",
                  dtype: str = "reference",
                  name: str = "current_loop.h",
                  motor: Motor | None = None) -> str:
    """Render the header. Raises if the closed loop is unstable."""
    if design_point not in DESIGN_POINTS:
        raise ValueError(f"unknown design point {design_point!r}; "
                         f"expected one of {sorted(DESIGN_POINTS)}")

    point = DESIGN_POINTS[design_point]
    motor = motor or Motor()

    result = next(r for r in sweep(point, [dtype], motor))
    if not result.stable:
        raise ValueError(
            f"closed loop is unstable at '{dtype}' for the {design_point} "
            f"design point (max|pole| = {result.max_pole:.5f}) — refusing to "
            f"export. Quantizing the notch to this type moves a pole onto "
            f"the unit circle; shipping these coefficients would put an "
            f"oscillator in the current loop.")

    c_num, c_den, gain = design_pi(motor, point.crossover_hz)
    n_num, n_den = design_notch(point)
    c_num, n_num = _quantize(c_num, dtype), _quantize(n_num, dtype)
    n_den = _quantize(n_den, dtype)

    guard = _guard(name)
    metrics = result.metrics

    lines = [_BANNER.format(
        name=name, point=point.name, rationale=point.rationale, dtype=dtype,
        rate=SAMPLE_RATE_HZ, crossover=point.crossover_hz,
        notch=point.notch_hz, notch_bw=point.notch_bandwidth_oct,
        depth=result.notch_depth_db, max_pole=result.max_pole,
        overshoot=metrics.get("overshoot_pct", float("nan")),
        resistance=motor.resistance_ohm, inductance=motor.inductance_h,
        tau=motor.electrical_tau_s * 1e6,
        version=mpdsp.__version__, dsp_version=mpdsp.__dsp_version__)]

    lines.append(f"#ifndef {guard}")
    lines.append(f"#define {guard}")
    lines.append("")
    lines.append(f"#define LOOP_RATE_HZ      {SAMPLE_RATE_HZ:.1f}")
    lines.append(f"#define LOOP_PERIOD_S     {1.0 / SAMPLE_RATE_HZ:.17g}")
    lines.append("")

    lines.append("/* PI current controller, C(z) = (PI_B0 + PI_B1 z^-1)")
    lines.append(" *                              / (1 - z^-1)")
    lines.append(" *")
    lines.append(" *   u[n] = u[n-1] + PI_B0*e[n] + PI_B1*e[n-1]")
    lines.append(" */")
    lines.append(f"#define PI_B0             {c_num[0]:.17g}")
    lines.append(f"#define PI_B1             {c_num[1]:.17g}")
    lines.append(f"#define PI_KP             {gain:.17g}")
    lines.append("")

    lines.append("/* Resonance notch, direct form I:")
    lines.append(" *")
    lines.append(" *   y[n] = NOTCH_B0*x[n] + NOTCH_B1*x[n-1] + NOTCH_B2*x[n-2]")
    lines.append(" *                        - NOTCH_A1*y[n-1] - NOTCH_A2*y[n-2]")
    lines.append(" */")
    for macro, value in (("NOTCH_B0", n_num[0]), ("NOTCH_B1", n_num[1]),
                         ("NOTCH_B2", n_num[2]), ("NOTCH_A1", n_den[1]),
                         ("NOTCH_A2", n_den[2])):
        lines.append(f"#define {macro:<17} {value:.17g}")
    lines.append(f"#define NOTCH_CENTER_HZ   {point.notch_hz:.1f}")
    lines.append("")

    lines.append(f"#endif /* {guard} */")
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--design-point", default="conservative",
                        choices=list(DESIGN_POINTS))
    parser.add_argument("--dtype", default="reference", choices=DEFAULT_DTYPES)
    parser.add_argument("--out", default=None)
    args = parser.parse_args()

    out = (Path(args.out) if args.out
           else Path(__file__).parent / "artifacts" / "current_loop.h")
    out.parent.mkdir(parents=True, exist_ok=True)

    try:
        text = render_header(args.design_point, args.dtype, name=out.name)
    except ValueError as exc:
        print(f"error: {exc}")
        return 1

    out.write_text(text)
    print(f"wrote {out} ({out.stat().st_size} bytes, {args.design_point} "
          f"point, coefficients in '{args.dtype}')")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
