"""Emit Xilinx `.coe` coefficient files for the DDC cascade.

    python demos/04_sdr_ddc_cascade/emit_coeffs_vivado.py
    python demos/04_sdr_ddc_cascade/emit_coeffs_vivado.py --bits 16

One file per stage, in the format the Vivado FIR Compiler and Block Memory
Generator read: a `radix` declaration followed by a comma-separated
`coefdata` list terminated with a semicolon.

Coefficients are signed integers at the requested width, with a shared
power-of-two scale per stage — the header records the fractional bit count
so the RTL knows how far to shift the accumulator back down. Radix 10 keeps
the file diffable; the Verilog emitter writes the same numbers as hex for
`$readmemh`.

Default width is 18 bits: the native coefficient port on a Xilinx DSP48E
slice, so anything at or below it costs one slice per tap. 14 bits is the
narrowest that meets this cascade's spec (see quantize_coefficients.py) —
worth using only if coefficient ROM is genuinely the binding constraint.
"""

from __future__ import annotations

import argparse
from pathlib import Path

import numpy as np

import mpdsp

from design import CascadeSpec, analyze_response, design_cascade
from quantize_coefficients import quantize_taps

DEFAULT_BITS = 18

_STAGE_NAMES = ["stage1_decim2", "stage2_decim2", "stage3_decim2",
                "stage4_sharp_decim2"]


def render_coe(taps: np.ndarray, num_bits: int, stage_name: str,
               stage_index: int, decimation: int) -> str:
    """Return the full text of one `.coe` file."""
    dequantized, codes, frac_bits = quantize_taps(taps, num_bits)
    error = float(np.max(np.abs(dequantized - taps)))

    lines = [
        f"; {stage_name} — DDC cascade stage {stage_index}",
        ";",
        "; Generated by demos/04_sdr_ddc_cascade/emit_coeffs_vivado.py",
        "; — do not edit.",
        ";",
        f"; mpdsp {mpdsp.__version__} (upstream sw::dsp "
        f"{mpdsp.__dsp_version__})",
        f"; taps          : {len(taps)}",
        f"; decimation    : {decimation}",
        f"; word length   : {num_bits} bits, signed",
        f"; scale         : 2^{frac_bits} "
        f"(divide the accumulator by this, i.e. >> {frac_bits})",
        f"; max tap error : {error:.3e}",
        ";",
        "; Load into the Vivado FIR Compiler as a coefficient file, or into",
        "; the Block Memory Generator as COE data.",
        "",
        "radix = 10;",
        "coefdata =",
    ]

    body = [f"  {int(code)}" for code in codes]
    lines.append(",\n".join(body) + ";")
    lines.append("")
    return "\n".join(lines)


def emit_all(outdir: Path, num_bits: int = DEFAULT_BITS,
             spec: CascadeSpec | None = None) -> list[Path]:
    """Write one `.coe` per stage. Returns the paths written."""
    spec = spec or CascadeSpec()
    stages = design_cascade(spec)
    outdir.mkdir(parents=True, exist_ok=True)

    written = []
    for index, taps in enumerate(stages):
        name = _STAGE_NAMES[index] if index < len(_STAGE_NAMES) \
            else f"stage{index + 1}"
        path = outdir / f"{name}.coe"
        path.write_text(render_coe(taps, num_bits, name, index + 1,
                                   decimation=2))
        written.append(path)
    return written


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--bits", type=int, default=DEFAULT_BITS,
                        help=f"coefficient word length (default "
                             f"{DEFAULT_BITS}, the DSP48E native width)")
    parser.add_argument("--outdir", default=None)
    args = parser.parse_args()

    outdir = (Path(args.outdir) if args.outdir
              else Path(__file__).parent / "artifacts" / "vivado")
    spec = CascadeSpec()
    written = emit_all(outdir, args.bits, spec)

    # Report what the chosen width actually costs, so the number is never
    # taken on faith.
    stages = design_cascade(spec)
    quantized = [quantize_taps(t, args.bits)[0] for t in stages]
    analysis = analyze_response(quantized)

    for path in written:
        print(f"wrote {path} ({path.stat().st_size} bytes)")
    print(f"\nat {args.bits} bits: passband ripple "
          f"{analysis['passband_ripple_db']:.4f} dB, alias attenuation "
          f"{analysis['alias_attenuation_db']:.1f} dB")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
