"""Emit `$readmemh` coefficient tables and a Verilog header for the cascade.

    python demos/04_sdr_ddc_cascade/emit_coeffs_verilog.py
    python demos/04_sdr_ddc_cascade/emit_coeffs_verilog.py --bits 16

Writes, per stage, a `.hex` file of two's-complement coefficients one per
line — the format `$readmemh` expects:

    reg signed [17:0] taps [0:50];
    initial $readmemh("stage1_decim2.hex", taps);

plus a single `cascade_params.vh` carrying the widths, tap counts, and
scale exponents, so the RTL does not hard-code numbers that the design
script owns.

Two's complement is written explicitly rather than relying on a formatter:
`$readmemh` reads raw bit patterns, so a negative coefficient has to appear
as its unsigned two's-complement image at exactly the declared width. Getting
that wrong yields a filter whose negative taps read as huge positives, which
is a silent and thoroughly confusing failure in simulation.
"""

from __future__ import annotations

import argparse
from pathlib import Path

import numpy as np

import mpdsp

from design import CascadeSpec, design_cascade
from quantize_coefficients import quantize_taps

DEFAULT_BITS = 18

_STAGE_NAMES = ["stage1_decim2", "stage2_decim2", "stage3_decim2",
                "stage4_sharp_decim2"]


def to_twos_complement(code: int, num_bits: int) -> int:
    """Unsigned image of a signed `code` at `num_bits` width."""
    limit = 1 << num_bits
    if not (-(limit >> 1) <= code < (limit >> 1)):
        raise ValueError(
            f"coefficient {code} does not fit in {num_bits} signed bits")
    return code & (limit - 1)


def render_hex(taps: np.ndarray, num_bits: int) -> str:
    """One two's-complement hex word per line, no prefixes.

    `$readmemh` does not accept comments in all tools, so this file carries
    data only; the metadata lives in the .vh header.
    """
    _, codes, _ = quantize_taps(taps, num_bits)
    digits = (num_bits + 3) // 4
    return "\n".join(
        f"{to_twos_complement(int(c), num_bits):0{digits}x}" for c in codes
    ) + "\n"


def render_params(stages: list[np.ndarray], num_bits: int) -> str:
    """A Verilog include with the shapes and scales the RTL needs."""
    lines = [
        "// cascade_params.vh — DDC cascade geometry",
        "//",
        "// Generated by demos/04_sdr_ddc_cascade/emit_coeffs_verilog.py",
        "// — do not edit.",
        "//",
        f"// mpdsp {mpdsp.__version__} "
        f"(upstream sw::dsp {mpdsp.__dsp_version__})",
        "//",
        "// Each stage decimates by 2; four stages give 16 overall.",
        "// Coefficients are signed, COEFF_WIDTH bits, scaled by",
        "// 2^STAGEn_FRAC — shift the accumulator right by that much.",
        "",
        "`ifndef CASCADE_PARAMS_VH",
        "`define CASCADE_PARAMS_VH",
        "",
        f"`define COEFF_WIDTH      {num_bits}",
        f"`define NUM_STAGES       {len(stages)}",
        f"`define STAGE_DECIMATION 2",
        f"`define TOTAL_DECIMATION {2 ** len(stages)}",
        "",
    ]
    for index, taps in enumerate(stages, start=1):
        _, _, frac_bits = quantize_taps(taps, num_bits)
        lines.append(f"`define STAGE{index}_TAPS {len(taps)}")
        lines.append(f"`define STAGE{index}_FRAC {frac_bits}")
    lines += ["", "`endif // CASCADE_PARAMS_VH", ""]
    return "\n".join(lines)


def emit_all(outdir: Path, num_bits: int = DEFAULT_BITS,
             spec: CascadeSpec | None = None) -> list[Path]:
    """Write per-stage .hex files plus cascade_params.vh."""
    spec = spec or CascadeSpec()
    stages = design_cascade(spec)
    outdir.mkdir(parents=True, exist_ok=True)

    written = []
    for index, taps in enumerate(stages):
        name = _STAGE_NAMES[index] if index < len(_STAGE_NAMES) \
            else f"stage{index + 1}"
        path = outdir / f"{name}.hex"
        path.write_text(render_hex(taps, num_bits))
        written.append(path)

    params = outdir / "cascade_params.vh"
    params.write_text(render_params(stages, num_bits))
    written.append(params)
    return written


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--bits", type=int, default=DEFAULT_BITS)
    parser.add_argument("--outdir", default=None)
    args = parser.parse_args()

    outdir = (Path(args.outdir) if args.outdir
              else Path(__file__).parent / "artifacts" / "verilog")
    for path in emit_all(outdir, args.bits):
        print(f"wrote {path} ({path.stat().st_size} bytes)")
    print(f"\n  reg signed [{args.bits - 1}:0] taps [0:N-1];")
    print('  initial $readmemh("stage1_decim2.hex", taps);')
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
